spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mariadb://localhost:3306/sopeu
    username: root
    password: qwer1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.spatial.dialect.mariadb.MariaDB103SpatialDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true


    logging.level:
    org.hibernate.SQL: debug
  #  org.hibernate.type: trace
